trigger:
- main
pool:
  vmImage: ubuntu-latest
  name: 'Azure Pipelines'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'